- name: Install git
  become: true
  ansible.builtin.package:
    state: present
    name:
      - git
      - git-lfs

- name: Install gitconfig
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    backup: true
    mode: "0644"
  tags:
    - user_config
