- name: Create ~/.bashrc
  ansible.builtin.copy:
    src: bashrc
    dest: "{{ ansible_env.HOME }}/.bashrc"
    mode: "0644"
    force: false # force false instead of backup true so user changes persist
  tags:
    - user_config

- name: Configure ~/.bash_aliases
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bash_aliases"
    block: "{{ lookup('file', 'bash_aliases') }}"
    marker: "# {mark} ANSIBLE ALIASES BLOCK"
    create: true
    mode: "0644"
  tags:
    - user_config

- name: Enable bash aliases
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "[ -f ~/.bash_aliases ] && source ~/.bash_aliases"

- name: Create ~/.local/bash-completion/completions
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bash-completion/completions"
    state: directory
    recurse: true

- name: Make bash tab complete case insensitive
  ansible.builtin.copy:
    src: inputrc
    dest: "{{ ansible_env.HOME }}/.inputrc"
    backup: true
    mode: "0644"
  tags:
    - user_config
