- name: Create Minecraft User
  become: true
  ansible.builtin.user:
    name: "{{ minecraft_user }}"
    password_lock: true
    system: true
    state: present
    shell: /usr/bin/nologin
    comment: User owning /opt/minecraft

- name: Add user to minecraft group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: "{{ minecraft_user }}"
    append: true

- name: Create /opt/minecraft
  become: true
  ansible.builtin.file:
    path: /opt/minecraft
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
    mode: "2770"

- name: Chown /opt/minecraft dir to minecraft user
  become: true
  ansible.builtin.file:
    path: /opt/minecraft
    state: directory
    recurse: true
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
