godot_url: "https://downloads.godotengine.org/?version={{ godot_version }}&flavor=stable&slug=linux.x86_64.zip&platform=linux.64"
godot_exec: "godot-{{ godot_version }}"
godot_build_path: "{{ ansible_env.HOME }}/.cache/dotfiles/build/godot"
