- name: Download installer
  ansible.builtin.get_url:
    url: https://pyenv.run
    dest: /tmp/pyenv.run
    mode: "0700"
    force: true

- name: Install Pyenv
  ansible.builtin.command: /tmp/pyenv.run
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv"
