- name: Install bash
  become: true
  ansible.builtin.package:
    name: bash
    state: present

- name: Install bash tab completion
  become: true
  ansible.builtin.package:
    name: bash-completion
    state: present
